/* ─── Real client logo gallery — exactly the logos shown on the company's
   official clients page (shrivaarielectricals.com/clients.html), fully
   downloaded into /public/images/clients-site/. No other logos are used.
   Category slugs follow the old site's industry grouping so the filter
   pills mirror the official classification. */

export interface GalleryClient {
  id: string
  num: number
  name: string
  src: string
  category: string
}

export const CLIENT_GALLERY: GalleryClient[] = [
  { id: 'c1', num: 1, name: 'Client 1', src: '/images/clients-site/1.jpg', category: 'auto' },
  { id: 'c2', num: 2, name: 'Client 2', src: '/images/clients-site/2.jpg', category: 'auto' },
  { id: 'c3', num: 3, name: 'Client 3', src: '/images/clients-site/3.jpg', category: 'auto' },
  { id: 'c4', num: 4, name: 'Client 4', src: '/images/clients-site/4.jpg', category: 'auto' },
  { id: 'c5', num: 5, name: 'Client 5', src: '/images/clients-site/5.jpg', category: 'auto' },
  { id: 'c6', num: 6, name: 'Client 6', src: '/images/clients-site/6.jpg', category: 'auto' },
  { id: 'c7', num: 7, name: 'Client 7', src: '/images/clients-site/7.jpg', category: 'auto' },
  { id: 'c8', num: 8, name: 'Client 8', src: '/images/clients-site/8.jpg', category: 'auto' },
  { id: 'c9', num: 9, name: 'Client 9', src: '/images/clients-site/9.jpg', category: 'auto' },
  { id: 'c10', num: 10, name: 'Client 10', src: '/images/clients-site/10.jpg', category: 'auto' },
  { id: 'c11', num: 11, name: 'Client 11', src: '/images/clients-site/11.jpg', category: 'auto' },
  { id: 'c12', num: 12, name: 'Client 12', src: '/images/clients-site/12.jpg', category: 'auto' },
  { id: 'c13', num: 13, name: 'Client 13', src: '/images/clients-site/13.jpg', category: 'auto' },
  { id: 'c14', num: 14, name: 'Client 14', src: '/images/clients-site/14.jpg', category: 'auto' },
  { id: 'c15', num: 15, name: 'Client 15', src: '/images/clients-site/15.jpg', category: 'auto' },
  { id: 'c16', num: 16, name: 'Client 16', src: '/images/clients-site/16.jpg', category: 'auto' },
  { id: 'c17', num: 17, name: 'Client 17', src: '/images/clients-site/17.jpg', category: 'auto' },
  { id: 'c18', num: 18, name: 'Client 18', src: '/images/clients-site/18.jpg', category: 'auto' },
  { id: 'c19', num: 19, name: 'Client 19', src: '/images/clients-site/19.jpg', category: 'auto' },
  { id: 'c20', num: 20, name: 'Client 20', src: '/images/clients-site/20.jpg', category: 'auto' },
  { id: 'c21', num: 21, name: 'Client 21', src: '/images/clients-site/21.jpg', category: 'auto' },
  { id: 'c22', num: 22, name: 'Client 22', src: '/images/clients-site/22.jpg', category: 'electronics' },
  { id: 'c23', num: 23, name: 'Client 23', src: '/images/clients-site/23.jpg', category: 'electronics' },
  { id: 'c24', num: 24, name: 'Client 24', src: '/images/clients-site/24.jpg', category: 'electronics' },
  { id: 'c25', num: 25, name: 'Client 25', src: '/images/clients-site/25.jpg', category: 'electronics' },
  { id: 'c26', num: 26, name: 'Client 26', src: '/images/clients-site/26.jpg', category: 'electronics' },
  { id: 'c27', num: 27, name: 'Client 27', src: '/images/clients-site/27.jpg', category: 'electronics' },
  { id: 'c28', num: 28, name: 'Client 28', src: '/images/clients-site/28.jpg', category: 'electronics' },
  { id: 'c29', num: 29, name: 'Client 29', src: '/images/clients-site/29.jpg', category: 'it' },
  { id: 'c30', num: 30, name: 'Client 30', src: '/images/clients-site/30.jpg', category: 'it' },
  { id: 'c31', num: 31, name: 'Client 31', src: '/images/clients-site/31.jpg', category: 'it' },
  { id: 'c32', num: 32, name: 'Client 32', src: '/images/clients-site/32.jpg', category: 'it' },
  { id: 'c33', num: 33, name: 'Client 33', src: '/images/clients-site/33.jpg', category: 'it' },
  { id: 'c34', num: 34, name: 'Client 34', src: '/images/clients-site/34.jpg', category: 'it' },
  { id: 'c35', num: 35, name: 'Client 35', src: '/images/clients-site/35.jpg', category: 'it' },
  { id: 'c36', num: 36, name: 'Client 36', src: '/images/clients-site/36.jpg', category: 'forging' },
  { id: 'c37', num: 37, name: 'Client 37', src: '/images/clients-site/37.jpg', category: 'forging' },
  { id: 'c38', num: 38, name: 'Client 38', src: '/images/clients-site/38.jpg', category: 'forging' },
  { id: 'c39', num: 39, name: 'Client 39', src: '/images/clients-site/39.jpg', category: 'forging' },
  { id: 'c40', num: 40, name: 'Client 40', src: '/images/clients-site/40.jpg', category: 'forging' },
  { id: 'c41', num: 41, name: 'Client 41', src: '/images/clients-site/41.jpg', category: 'auto' },
  { id: 'c42', num: 42, name: 'Client 42', src: '/images/clients-site/42.jpg', category: 'general' },
  { id: 'c43', num: 43, name: 'Client 43', src: '/images/clients-site/43.jpg', category: 'forging' },
  { id: 'c44', num: 44, name: 'Client 44', src: '/images/clients-site/44.jpg', category: 'forging' },
  { id: 'c45', num: 45, name: 'Client 45', src: '/images/clients-site/45.jpg', category: 'power' },
  { id: 'c46', num: 46, name: 'Client 46', src: '/images/clients-site/46.jpg', category: 'power' },
  { id: 'c47', num: 47, name: 'Client 47', src: '/images/clients-site/47.jpg', category: 'power' },
  { id: 'c48', num: 48, name: 'Client 48', src: '/images/clients-site/48.jpg', category: 'power' },
  { id: 'c49', num: 49, name: 'Client 49', src: '/images/clients-site/49.jpg', category: 'power' },
  { id: 'c50', num: 50, name: 'Client 50', src: '/images/clients-site/50.jpg', category: 'power' },
  { id: 'c51', num: 51, name: 'Client 51', src: '/images/clients-site/51.jpg', category: 'power' },
  { id: 'c52', num: 52, name: 'Client 52', src: '/images/clients-site/52.jpg', category: 'mnc' },
  { id: 'c53', num: 53, name: 'Client 53', src: '/images/clients-site/53.jpg', category: 'mnc' },
  { id: 'c54', num: 54, name: 'Client 54', src: '/images/clients-site/54.jpg', category: 'mnc' },
  { id: 'c55', num: 55, name: 'Client 55', src: '/images/clients-site/55.jpg', category: 'mnc' },
  { id: 'c56', num: 56, name: 'Client 56', src: '/images/clients-site/56.jpg', category: 'mnc' },
  { id: 'c57', num: 57, name: 'Client 57', src: '/images/clients-site/57.jpg', category: 'mnc' },
  { id: 'c58', num: 58, name: 'Client 58', src: '/images/clients-site/58.jpg', category: 'mnc' },
  { id: 'c59', num: 59, name: 'Client 59', src: '/images/clients-site/59.jpg', category: 'mnc' },
  { id: 'c60', num: 60, name: 'Client 60', src: '/images/clients-site/60.jpg', category: 'hit' },
  { id: 'c61', num: 61, name: 'Client 61', src: '/images/clients-site/61.jpg', category: 'hit' },
  { id: 'c62', num: 62, name: 'Client 62', src: '/images/clients-site/62.jpg', category: 'hit' },
  { id: 'c63', num: 63, name: 'Client 63', src: '/images/clients-site/63.jpg', category: 'hit' },
  { id: 'c64', num: 64, name: 'Client 64', src: '/images/clients-site/64.jpg', category: 'hit' },
  { id: 'c65', num: 65, name: 'Client 65', src: '/images/clients-site/65.jpg', category: 'hit' },
  { id: 'c66', num: 66, name: 'Client 66', src: '/images/clients-site/66.jpg', category: 'hit' },
  { id: 'c67', num: 67, name: 'Client 67', src: '/images/clients-site/67.jpg', category: 'hit' },
  { id: 'c68', num: 68, name: 'Client 68', src: '/images/clients-site/68.jpg', category: 'hit' },
  { id: 'c69', num: 69, name: 'Client 69', src: '/images/clients-site/69.jpg', category: 'hit' },
  { id: 'c70', num: 70, name: 'Client 70', src: '/images/clients-site/70.jpg', category: 'hit' },
  { id: 'c71', num: 71, name: 'Client 71', src: '/images/clients-site/71.jpg', category: 'hit' },
  { id: 'c72', num: 72, name: 'Client 72', src: '/images/clients-site/72.jpg', category: 'hit' },
  { id: 'c73', num: 73, name: 'Client 73', src: '/images/clients-site/73.jpg', category: 'hit' },
  { id: 'c74', num: 74, name: 'Client 74', src: '/images/clients-site/74.jpg', category: 'hit' },
  { id: 'c75', num: 75, name: 'Client 75', src: '/images/clients-site/75.jpg', category: 'cranes' },
  { id: 'c76', num: 76, name: 'Client 76', src: '/images/clients-site/76.jpg', category: 'cranes' },
  { id: 'c77', num: 77, name: 'Client 77', src: '/images/clients-site/77.jpg', category: 'cranes' },
  { id: 'c78', num: 78, name: 'Client 78', src: '/images/clients-site/78.jpg', category: 'general' },
  { id: 'c79', num: 79, name: 'Client 79', src: '/images/clients-site/79.jpg', category: 'general' },
  { id: 'c80', num: 80, name: 'Client 80', src: '/images/clients-site/80.jpg', category: 'granites' },
  { id: 'c81', num: 81, name: 'Client 81', src: '/images/clients-site/81.jpg', category: 'general' },
  { id: 'c82', num: 82, name: 'Client 82', src: '/images/clients-site/82.jpg', category: 'general' },
  { id: 'c83', num: 83, name: 'Client 83', src: '/images/clients-site/83.jpg', category: 'general' },
  { id: 'c84', num: 84, name: 'Client 84', src: '/images/clients-site/84.jpg', category: 'general' },
  { id: 'c85', num: 85, name: 'Client 85', src: '/images/clients-site/85.jpg', category: 'general' },
  { id: 'c86', num: 86, name: 'Client 86', src: '/images/clients-site/86.jpg', category: 'metal' },
  { id: 'c87', num: 87, name: 'Client 87', src: '/images/clients-site/87.jpg', category: 'metal' },
  { id: 'c88', num: 88, name: 'Client 88', src: '/images/clients-site/88.jpg', category: 'metal' },
  { id: 'c89', num: 89, name: 'Client 89', src: '/images/clients-site/89.jpg', category: 'metal' },
  { id: 'c90', num: 90, name: 'Client 90', src: '/images/clients-site/90.jpg', category: 'metal' },
  { id: 'c91', num: 91, name: 'Client 91', src: '/images/clients-site/91.jpg', category: 'metal' },
  { id: 'c92', num: 92, name: 'Client 92', src: '/images/clients-site/92.jpg', category: 'real' },
  { id: 'c93', num: 93, name: 'Client 93', src: '/images/clients-site/93.jpg', category: 'real' },
  { id: 'c94', num: 94, name: 'Client 94', src: '/images/clients-site/94.jpg', category: 'real' },
  { id: 'c95', num: 95, name: 'Client 95', src: '/images/clients-site/95.jpg', category: 'real' },
  { id: 'c96', num: 96, name: 'Client 96', src: '/images/clients-site/96.jpg', category: 'real' },
  { id: 'c97', num: 97, name: 'Client 97', src: '/images/clients-site/97.jpg', category: 'real' },
  { id: 'c98', num: 98, name: 'Client 98', src: '/images/clients-site/98.jpg', category: 'real' },
  { id: 'c99', num: 99, name: 'Client 99', src: '/images/clients-site/99.jpg', category: 'real' },
  { id: 'c100', num: 100, name: 'Client 100', src: '/images/clients-site/100.jpg', category: 'real' },
  { id: 'c101', num: 101, name: 'Client 101', src: '/images/clients-site/101.jpg', category: 'petro' },
  { id: 'c102', num: 102, name: 'Client 102', src: '/images/clients-site/102.jpg', category: 'petro' },
  { id: 'c103', num: 103, name: 'Client 103', src: '/images/clients-site/103.jpg', category: 'petro' },
  { id: 'c104', num: 104, name: 'Client 104', src: '/images/clients-site/104.jpg', category: 'petro' },
  { id: 'c105', num: 105, name: 'Client 105', src: '/images/clients-site/105.jpg', category: 'petro' },
  { id: 'c106', num: 106, name: 'Client 106', src: '/images/clients-site/106.jpg', category: 'petro' },
  { id: 'c107', num: 107, name: 'Client 107', src: '/images/clients-site/107.jpg', category: 'petro' },
  { id: 'c108', num: 108, name: 'Client 108', src: '/images/clients-site/108.jpg', category: 'chem' },
  { id: 'c109', num: 109, name: 'Client 109', src: '/images/clients-site/109.jpg', category: 'govt' },
  { id: 'c110', num: 110, name: 'Client 110', src: '/images/clients-site/110.jpg', category: 'govt' },
  { id: 'c111', num: 111, name: 'Client 111', src: '/images/clients-site/111.jpg', category: 'govt' },
  { id: 'c112', num: 112, name: 'Client 112', src: '/images/clients-site/112.jpg', category: 'govt' },
  { id: 'c113', num: 113, name: 'Client 113', src: '/images/clients-site/113.jpg', category: 'govt' },
  { id: 'c114', num: 114, name: 'Client 114', src: '/images/clients-site/114.jpg', category: 'govt' },
  { id: 'c115', num: 115, name: 'Client 115', src: '/images/clients-site/115.jpg', category: 'govt' },
  { id: 'c116', num: 116, name: 'Client 116', src: '/images/clients-site/116.jpg', category: 'govt' },
  { id: 'c117', num: 117, name: 'Client 117', src: '/images/clients-site/117.jpg', category: 'govt' },
  { id: 'c118', num: 118, name: 'Client 118', src: '/images/clients-site/118.jpg', category: 'govt' },
  { id: 'c119', num: 119, name: 'Client 119', src: '/images/clients-site/119.jpg', category: 'govt' },
  { id: 'c120', num: 120, name: 'Client 120', src: '/images/clients-site/120.jpg', category: 'govt' },
  { id: 'c121', num: 121, name: 'Client 121', src: '/images/clients-site/121.jpg', category: 'govt' },
  { id: 'c122', num: 122, name: 'Client 122', src: '/images/clients-site/122.jpg', category: 'media' },
  { id: 'c123', num: 123, name: 'Client 123', src: '/images/clients-site/123.jpg', category: 'media' },
  { id: 'c124', num: 124, name: 'Client 124', src: '/images/clients-site/124.jpg', category: 'media' },
  { id: 'c125', num: 125, name: 'Client 125', src: '/images/clients-site/125.jpg', category: 'pharma' },
  { id: 'c126', num: 126, name: 'Client 126', src: '/images/clients-site/126.jpg', category: 'pharma' },
  { id: 'c127', num: 127, name: 'Client 127', src: '/images/clients-site/127.jpg', category: 'textiles' },
  { id: 'c128', num: 128, name: 'Client 128', src: '/images/clients-site/128.jpg', category: 'food' },
  { id: 'c129', num: 129, name: 'Client 129', src: '/images/clients-site/129.jpg', category: 'food' },
  { id: 'c130', num: 130, name: 'Client 130', src: '/images/clients-site/130.jpg', category: 'food' },
  { id: 'c131', num: 131, name: 'Client 131', src: '/images/clients-site/131.jpg', category: 'food' },
  { id: 'c132', num: 132, name: 'Client 132', src: '/images/clients-site/132.jpg', category: 'food' },
  { id: 'c133', num: 133, name: 'Client 133', src: '/images/clients-site/133.jpg', category: 'food' },
  { id: 'c134', num: 134, name: 'Client 134', src: '/images/clients-site/134.jpg', category: 'food' },
  { id: 'c135', num: 135, name: 'Client 135', src: '/images/clients-site/135.jpg', category: 'metal' },
  { id: 'c136', num: 136, name: 'Client 136', src: '/images/clients-site/136.jpg', category: 'granites' },
  { id: 'c169', num: 169, name: 'Client 137', src: '/images/clients-site/169.jpg', category: 'airport' },
  { id: 'c170', num: 170, name: 'Client 138', src: '/images/clients-site/170.jpg', category: 'auto' },
  { id: 'c171', num: 171, name: 'Client 139', src: '/images/clients-site/171.jpg', category: 'carbon' },
  { id: 'c172', num: 172, name: 'Client 140', src: '/images/clients-site/172.jpg', category: 'chem' },
  { id: 'c173', num: 173, name: 'Client 141', src: '/images/clients-site/173.jpg', category: 'chem' },
  { id: 'c174', num: 174, name: 'Client 142', src: '/images/clients-site/174.jpg', category: 'chem' },
  { id: 'c175', num: 175, name: 'Client 143', src: '/images/clients-site/175.jpg', category: 'commercial' },
  { id: 'c176', num: 176, name: 'Client 144', src: '/images/clients-site/176.jpg', category: 'general' },
  { id: 'c177', num: 177, name: 'Client 145', src: '/images/clients-site/177.jpg', category: 'it' },
  { id: 'c178', num: 178, name: 'Client 146', src: '/images/clients-site/178.jpg', category: 'it' },
  { id: 'c179', num: 179, name: 'Client 147', src: '/images/clients-site/179.jpg', category: 'engg' },
  { id: 'c180', num: 180, name: 'Client 148', src: '/images/clients-site/180.jpg', category: 'engg' },
  { id: 'c181', num: 181, name: 'Client 149', src: '/images/clients-site/181.jpg', category: 'engg' },
  { id: 'c183', num: 183, name: 'Client 150', src: '/images/clients-site/183.jpg', category: 'govt' },
  { id: 'c184', num: 184, name: 'Client 151', src: '/images/clients-site/184.jpg', category: 'electronics' },
  { id: 'c185', num: 185, name: 'Client 152', src: '/images/clients-site/185.jpg', category: 'electronics' },
  { id: 'c186', num: 186, name: 'Client 153', src: '/images/clients-site/186.jpg', category: 'hit' },
  { id: 'c187', num: 187, name: 'Client 154', src: '/images/clients-site/187.jpg', category: 'hit' },
  { id: 'c188', num: 188, name: 'Client 155', src: '/images/clients-site/188.jpg', category: 'commercial' },
  { id: 'c189', num: 189, name: 'Client 156', src: '/images/clients-site/189.jpg', category: 'commercial' },
  { id: 'c190', num: 190, name: 'Client 157', src: '/images/clients-site/190.jpg', category: 'commercial' },
  { id: 'c191', num: 191, name: 'Client 158', src: '/images/clients-site/191.jpg', category: 'commercial' },
  { id: 'c192', num: 192, name: 'Client 159', src: '/images/clients-site/192.jpg', category: 'commercial' },
  { id: 'c193', num: 193, name: 'Client 160', src: '/images/clients-site/193.jpg', category: 'general' },
  { id: 'c194', num: 194, name: 'Client 161', src: '/images/clients-site/194.jpg', category: 'metal' },
]

export const CATEGORY_LABELS: Record<string, string> = {
  airport: 'Airport',
  auto: 'Auto & Ancillary',
  carbon: 'Carbon',
  chem: 'Chemicals',
  commercial: 'Commercial',
  cranes: 'Cranes',
  electronics: 'Electronics',
  engg: 'Engineering',
  food: 'Food Industry',
  forging: 'Forging',
  general: 'Others',
  govt: 'Government',
  granites: 'Granites',
  hit: 'Hospitals & Institutions',
  it: 'IT & Technology',
  media: 'Media',
  metal: 'Metal & Steel',
  mnc: 'MNC',
  petro: 'Petroleum & Oil',
  pharma: 'Pharma',
  power: 'Power & Energy',
  real: 'Real Estate',
  textiles: 'Textiles',
}
