/* ─── Real client logo gallery — exactly the logos shown on the company's
   official clients page (shrivaarielectricals.com/clients.html), fully
   downloaded into /public/images/clients-site/. No other logos are used.
   Category slugs follow the old site's industry grouping so the filter
   pills mirror the official classification. */

export interface GalleryClient {
  id: string
  num: number
  src: string
  category: string
}

export const CLIENT_GALLERY: GalleryClient[] = [
  { id: 'c1', num: 1, src: '/images/clients-site/1.jpg', category: 'auto' },
  { id: 'c2', num: 2, src: '/images/clients-site/2.jpg', category: 'auto' },
  { id: 'c3', num: 3, src: '/images/clients-site/3.jpg', category: 'auto' },
  { id: 'c4', num: 4, src: '/images/clients-site/4.jpg', category: 'auto' },
  { id: 'c5', num: 5, src: '/images/clients-site/5.jpg', category: 'auto' },
  { id: 'c6', num: 6, src: '/images/clients-site/6.jpg', category: 'auto' },
  { id: 'c7', num: 7, src: '/images/clients-site/7.jpg', category: 'auto' },
  { id: 'c8', num: 8, src: '/images/clients-site/8.jpg', category: 'auto' },
  { id: 'c9', num: 9, src: '/images/clients-site/9.jpg', category: 'auto' },
  { id: 'c10', num: 10, src: '/images/clients-site/10.jpg', category: 'auto' },
  { id: 'c11', num: 11, src: '/images/clients-site/11.jpg', category: 'auto' },
  { id: 'c12', num: 12, src: '/images/clients-site/12.jpg', category: 'auto' },
  { id: 'c13', num: 13, src: '/images/clients-site/13.jpg', category: 'auto' },
  { id: 'c14', num: 14, src: '/images/clients-site/14.jpg', category: 'auto' },
  { id: 'c15', num: 15, src: '/images/clients-site/15.jpg', category: 'auto' },
  { id: 'c16', num: 16, src: '/images/clients-site/16.jpg', category: 'auto' },
  { id: 'c17', num: 17, src: '/images/clients-site/17.jpg', category: 'auto' },
  { id: 'c18', num: 18, src: '/images/clients-site/18.jpg', category: 'auto' },
  { id: 'c19', num: 19, src: '/images/clients-site/19.jpg', category: 'auto' },
  { id: 'c20', num: 20, src: '/images/clients-site/20.jpg', category: 'auto' },
  { id: 'c21', num: 21, src: '/images/clients-site/21.jpg', category: 'auto' },
  { id: 'c22', num: 22, src: '/images/clients-site/22.jpg', category: 'electronics' },
  { id: 'c23', num: 23, src: '/images/clients-site/23.jpg', category: 'electronics' },
  { id: 'c24', num: 24, src: '/images/clients-site/24.jpg', category: 'electronics' },
  { id: 'c25', num: 25, src: '/images/clients-site/25.jpg', category: 'electronics' },
  { id: 'c26', num: 26, src: '/images/clients-site/26.jpg', category: 'electronics' },
  { id: 'c27', num: 27, src: '/images/clients-site/27.jpg', category: 'electronics' },
  { id: 'c28', num: 28, src: '/images/clients-site/28.jpg', category: 'electronics' },
  { id: 'c29', num: 29, src: '/images/clients-site/29.jpg', category: 'it' },
  { id: 'c30', num: 30, src: '/images/clients-site/30.jpg', category: 'it' },
  { id: 'c31', num: 31, src: '/images/clients-site/31.jpg', category: 'it' },
  { id: 'c32', num: 32, src: '/images/clients-site/32.jpg', category: 'it' },
  { id: 'c33', num: 33, src: '/images/clients-site/33.jpg', category: 'it' },
  { id: 'c34', num: 34, src: '/images/clients-site/34.jpg', category: 'it' },
  { id: 'c35', num: 35, src: '/images/clients-site/35.jpg', category: 'it' },
  { id: 'c36', num: 36, src: '/images/clients-site/36.jpg', category: 'forging' },
  { id: 'c37', num: 37, src: '/images/clients-site/37.jpg', category: 'forging' },
  { id: 'c38', num: 38, src: '/images/clients-site/38.jpg', category: 'forging' },
  { id: 'c39', num: 39, src: '/images/clients-site/39.jpg', category: 'forging' },
  { id: 'c40', num: 40, src: '/images/clients-site/40.jpg', category: 'forging' },
  { id: 'c41', num: 41, src: '/images/clients-site/41.jpg', category: 'auto' },
  { id: 'c42', num: 42, src: '/images/clients-site/42.jpg', category: 'general' },
  { id: 'c43', num: 43, src: '/images/clients-site/43.jpg', category: 'forging' },
  { id: 'c44', num: 44, src: '/images/clients-site/44.jpg', category: 'forging' },
  { id: 'c45', num: 45, src: '/images/clients-site/45.jpg', category: 'power' },
  { id: 'c46', num: 46, src: '/images/clients-site/46.jpg', category: 'power' },
  { id: 'c47', num: 47, src: '/images/clients-site/47.jpg', category: 'power' },
  { id: 'c48', num: 48, src: '/images/clients-site/48.jpg', category: 'power' },
  { id: 'c49', num: 49, src: '/images/clients-site/49.jpg', category: 'power' },
  { id: 'c50', num: 50, src: '/images/clients-site/50.jpg', category: 'power' },
  { id: 'c51', num: 51, src: '/images/clients-site/51.jpg', category: 'power' },
  { id: 'c52', num: 52, src: '/images/clients-site/52.jpg', category: 'mnc' },
  { id: 'c53', num: 53, src: '/images/clients-site/53.jpg', category: 'mnc' },
  { id: 'c54', num: 54, src: '/images/clients-site/54.jpg', category: 'mnc' },
  { id: 'c55', num: 55, src: '/images/clients-site/55.jpg', category: 'mnc' },
  { id: 'c56', num: 56, src: '/images/clients-site/56.jpg', category: 'mnc' },
  { id: 'c57', num: 57, src: '/images/clients-site/57.jpg', category: 'mnc' },
  { id: 'c58', num: 58, src: '/images/clients-site/58.jpg', category: 'mnc' },
  { id: 'c59', num: 59, src: '/images/clients-site/59.jpg', category: 'mnc' },
  { id: 'c60', num: 60, src: '/images/clients-site/60.jpg', category: 'hit' },
  { id: 'c61', num: 61, src: '/images/clients-site/61.jpg', category: 'hit' },
  { id: 'c62', num: 62, src: '/images/clients-site/62.jpg', category: 'hit' },
  { id: 'c63', num: 63, src: '/images/clients-site/63.jpg', category: 'hit' },
  { id: 'c64', num: 64, src: '/images/clients-site/64.jpg', category: 'hit' },
  { id: 'c65', num: 65, src: '/images/clients-site/65.jpg', category: 'hit' },
  { id: 'c66', num: 66, src: '/images/clients-site/66.jpg', category: 'hit' },
  { id: 'c67', num: 67, src: '/images/clients-site/67.jpg', category: 'hit' },
  { id: 'c68', num: 68, src: '/images/clients-site/68.jpg', category: 'hit' },
  { id: 'c69', num: 69, src: '/images/clients-site/69.jpg', category: 'hit' },
  { id: 'c70', num: 70, src: '/images/clients-site/70.jpg', category: 'hit' },
  { id: 'c71', num: 71, src: '/images/clients-site/71.jpg', category: 'hit' },
  { id: 'c72', num: 72, src: '/images/clients-site/72.jpg', category: 'hit' },
  { id: 'c73', num: 73, src: '/images/clients-site/73.jpg', category: 'hit' },
  { id: 'c74', num: 74, src: '/images/clients-site/74.jpg', category: 'hit' },
  { id: 'c75', num: 75, src: '/images/clients-site/75.jpg', category: 'cranes' },
  { id: 'c76', num: 76, src: '/images/clients-site/76.jpg', category: 'cranes' },
  { id: 'c77', num: 77, src: '/images/clients-site/77.jpg', category: 'cranes' },
  { id: 'c78', num: 78, src: '/images/clients-site/78.jpg', category: 'general' },
  { id: 'c79', num: 79, src: '/images/clients-site/79.jpg', category: 'general' },
  { id: 'c80', num: 80, src: '/images/clients-site/80.jpg', category: 'granites' },
  { id: 'c81', num: 81, src: '/images/clients-site/81.jpg', category: 'general' },
  { id: 'c82', num: 82, src: '/images/clients-site/82.jpg', category: 'general' },
  { id: 'c83', num: 83, src: '/images/clients-site/83.jpg', category: 'general' },
  { id: 'c84', num: 84, src: '/images/clients-site/84.jpg', category: 'general' },
  { id: 'c85', num: 85, src: '/images/clients-site/85.jpg', category: 'general' },
  { id: 'c86', num: 86, src: '/images/clients-site/86.jpg', category: 'metal' },
  { id: 'c87', num: 87, src: '/images/clients-site/87.jpg', category: 'metal' },
  { id: 'c88', num: 88, src: '/images/clients-site/88.jpg', category: 'metal' },
  { id: 'c89', num: 89, src: '/images/clients-site/89.jpg', category: 'metal' },
  { id: 'c90', num: 90, src: '/images/clients-site/90.jpg', category: 'metal' },
  { id: 'c91', num: 91, src: '/images/clients-site/91.jpg', category: 'metal' },
  { id: 'c92', num: 92, src: '/images/clients-site/92.jpg', category: 'real' },
  { id: 'c93', num: 93, src: '/images/clients-site/93.jpg', category: 'real' },
  { id: 'c94', num: 94, src: '/images/clients-site/94.jpg', category: 'real' },
  { id: 'c95', num: 95, src: '/images/clients-site/95.jpg', category: 'real' },
  { id: 'c96', num: 96, src: '/images/clients-site/96.jpg', category: 'real' },
  { id: 'c97', num: 97, src: '/images/clients-site/97.jpg', category: 'real' },
  { id: 'c98', num: 98, src: '/images/clients-site/98.jpg', category: 'real' },
  { id: 'c99', num: 99, src: '/images/clients-site/99.jpg', category: 'real' },
  { id: 'c100', num: 100, src: '/images/clients-site/100.jpg', category: 'real' },
  { id: 'c101', num: 101, src: '/images/clients-site/101.jpg', category: 'petro' },
  { id: 'c102', num: 102, src: '/images/clients-site/102.jpg', category: 'petro' },
  { id: 'c103', num: 103, src: '/images/clients-site/103.jpg', category: 'petro' },
  { id: 'c104', num: 104, src: '/images/clients-site/104.jpg', category: 'petro' },
  { id: 'c105', num: 105, src: '/images/clients-site/105.jpg', category: 'petro' },
  { id: 'c106', num: 106, src: '/images/clients-site/106.jpg', category: 'petro' },
  { id: 'c107', num: 107, src: '/images/clients-site/107.jpg', category: 'petro' },
  { id: 'c108', num: 108, src: '/images/clients-site/108.jpg', category: 'chem' },
  { id: 'c109', num: 109, src: '/images/clients-site/109.jpg', category: 'govt' },
  { id: 'c110', num: 110, src: '/images/clients-site/110.jpg', category: 'govt' },
  { id: 'c111', num: 111, src: '/images/clients-site/111.jpg', category: 'govt' },
  { id: 'c112', num: 112, src: '/images/clients-site/112.jpg', category: 'govt' },
  { id: 'c113', num: 113, src: '/images/clients-site/113.jpg', category: 'govt' },
  { id: 'c114', num: 114, src: '/images/clients-site/114.jpg', category: 'govt' },
  { id: 'c115', num: 115, src: '/images/clients-site/115.jpg', category: 'govt' },
  { id: 'c116', num: 116, src: '/images/clients-site/116.jpg', category: 'govt' },
  { id: 'c117', num: 117, src: '/images/clients-site/117.jpg', category: 'govt' },
  { id: 'c118', num: 118, src: '/images/clients-site/118.jpg', category: 'govt' },
  { id: 'c119', num: 119, src: '/images/clients-site/119.jpg', category: 'govt' },
  { id: 'c120', num: 120, src: '/images/clients-site/120.jpg', category: 'govt' },
  { id: 'c121', num: 121, src: '/images/clients-site/121.jpg', category: 'govt' },
  { id: 'c122', num: 122, src: '/images/clients-site/122.jpg', category: 'media' },
  { id: 'c123', num: 123, src: '/images/clients-site/123.jpg', category: 'media' },
  { id: 'c124', num: 124, src: '/images/clients-site/124.jpg', category: 'media' },
  { id: 'c125', num: 125, src: '/images/clients-site/125.jpg', category: 'pharma' },
  { id: 'c126', num: 126, src: '/images/clients-site/126.jpg', category: 'pharma' },
  { id: 'c127', num: 127, src: '/images/clients-site/127.jpg', category: 'textiles' },
  { id: 'c128', num: 128, src: '/images/clients-site/128.jpg', category: 'food' },
  { id: 'c129', num: 129, src: '/images/clients-site/129.jpg', category: 'food' },
  { id: 'c130', num: 130, src: '/images/clients-site/130.jpg', category: 'food' },
  { id: 'c131', num: 131, src: '/images/clients-site/131.jpg', category: 'food' },
  { id: 'c132', num: 132, src: '/images/clients-site/132.jpg', category: 'food' },
  { id: 'c133', num: 133, src: '/images/clients-site/133.jpg', category: 'food' },
  { id: 'c134', num: 134, src: '/images/clients-site/134.jpg', category: 'food' },
  { id: 'c135', num: 135, src: '/images/clients-site/135.jpg', category: 'metal' },
  { id: 'c136', num: 136, src: '/images/clients-site/136.jpg', category: 'granites' },
  { id: 'c169', num: 169, src: '/images/clients-site/169.jpg', category: 'airport' },
  { id: 'c170', num: 170, src: '/images/clients-site/170.jpg', category: 'auto' },
  { id: 'c171', num: 171, src: '/images/clients-site/171.jpg', category: 'carbon' },
  { id: 'c172', num: 172, src: '/images/clients-site/172.jpg', category: 'chem' },
  { id: 'c173', num: 173, src: '/images/clients-site/173.jpg', category: 'chem' },
  { id: 'c174', num: 174, src: '/images/clients-site/174.jpg', category: 'chem' },
  { id: 'c175', num: 175, src: '/images/clients-site/175.jpg', category: 'commercial' },
  { id: 'c176', num: 176, src: '/images/clients-site/176.jpg', category: 'general' },
  { id: 'c177', num: 177, src: '/images/clients-site/177.jpg', category: 'it' },
  { id: 'c178', num: 178, src: '/images/clients-site/178.jpg', category: 'it' },
  { id: 'c179', num: 179, src: '/images/clients-site/179.jpg', category: 'engg' },
  { id: 'c180', num: 180, src: '/images/clients-site/180.jpg', category: 'engg' },
  { id: 'c181', num: 181, src: '/images/clients-site/181.jpg', category: 'engg' },
  { id: 'c183', num: 183, src: '/images/clients-site/183.jpg', category: 'govt' },
  { id: 'c184', num: 184, src: '/images/clients-site/184.jpg', category: 'electronics' },
  { id: 'c185', num: 185, src: '/images/clients-site/185.jpg', category: 'electronics' },
  { id: 'c186', num: 186, src: '/images/clients-site/186.jpg', category: 'hit' },
  { id: 'c187', num: 187, src: '/images/clients-site/187.jpg', category: 'hit' },
  { id: 'c188', num: 188, src: '/images/clients-site/188.jpg', category: 'commercial' },
  { id: 'c189', num: 189, src: '/images/clients-site/189.jpg', category: 'commercial' },
  { id: 'c190', num: 190, src: '/images/clients-site/190.jpg', category: 'commercial' },
  { id: 'c191', num: 191, src: '/images/clients-site/191.jpg', category: 'commercial' },
  { id: 'c192', num: 192, src: '/images/clients-site/192.jpg', category: 'commercial' },
  { id: 'c193', num: 193, src: '/images/clients-site/193.jpg', category: 'general' },
  { id: 'c194', num: 194, src: '/images/clients-site/194.jpg', category: 'metal' },
]

export const CATEGORY_LABELS: Record<string, string> = {
  airport: 'Airport',
  auto: 'Auto & Ancillary',
  carbon: 'Carbon',
  chem: 'Chemicals',
  commercial: 'Commercial',
  cranes: 'Cranes',
  electronics: 'Electronics',
  engg: 'Engineering',
  food: 'Food Industry',
  forging: 'Forging',
  general: 'Others',
  govt: 'Government',
  granites: 'Granites',
  hit: 'Hospitals & Institutions',
  it: 'IT & Technology',
  media: 'Media',
  metal: 'Metal & Steel',
  mnc: 'MNC',
  petro: 'Petroleum & Oil',
  pharma: 'Pharma',
  power: 'Power & Energy',
  real: 'Real Estate',
  textiles: 'Textiles',
}
